### ISSUE TITLE
[wanionlib]: Something really bad happened on Integration at load stage POST_INIT

### ISSUE THREAD

**Issue by chezpaul** [WanionCane/WanionLib#1]
I just updated to the latest Thermal updates that came out June 10th.
ThermalExpansion-1.10.2-5.1.1.93-universal
ThermalFoundation-1.10.2-2.1.0.82-universal
RedstoneArsenal-1.10.2-2.0.4.33-universal
CoFHCore-1.10.2-4.1.2.157-universal

And now I get on my 1.10.2 server running Forge 2316 this error: [https://pastebin.com/291FNzpx](https://pastebin.com/291FNzpx)

Full server log: [https://pastebin.com/PZShsg9m](https://pastebin.com/PZShsg9m)

And it seems like I'll be able to play for 5 minutes and then server crashes.
I go back to backup without these changes and server works fine.
Thanks

**Comment by WanionCane** [comment]
thanks for letting me know, I need to update TE Integration :)
but, I really don't think that this would cause your server to crash.

**Comment by WanionCane** [comment]
oh, and, this is an UniDict issue, not WanionLib XD

**Comment by chezpaul** [comment]
Yes I do use UniDict... thanks for that by the way, makes the game so much easier...
I'll admit that I had changed a bunch of mods at once... 
Without updating ProjectRed to 4.8.3.47 and without adding Thermal Dynamic (which is new to 1.10.2), I don't get the server crashes anymore. So sorry to have blamed it on WanionLib.  ;-(

But you have to admit it is a scary error to see.  ;-)

**Comment by WanionCane** [comment]
yeah =P
really soon I am going to release an update for UniDict, just gimme some minutes.

**Comment by WanionCane** [comment]
could you try this? [UniDict-1.10.2-2.9.jar](https://minecraft.curseforge.com/projects/unidict/files/2432500)

**Comment by chezpaul** [comment]
Man, don't be so fast next time, I almost had to wait. ;-)
Yeah, that fixed it
Thanks

**Comment by WanionCane** [comment]
amazing, thanks XD
