### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by xJon** [WanionCane/WanionLib#11]
It'd be great to have changelogs posted in CurseForge or at least in commit details for modpack authors to know whether they should expect any specific changes. Thanks!

**Comment by WanionCane** [comment]
WanionLib is just a library, every change reflects in some of my mods, and most changes are just quality of life improvements (for me)
so, I don't see why making a changelog to it be something like this:

> removed the final modifier of method x

thanks for the comment :D
