### ISSUE TITLE
Crash with Stoneblock upon adding AvaritiaAddons

### ISSUE THREAD

**Issue by TheDisturbedDragon** [WanionCane/WanionLib#12]
I was trying to get the Infinity Chest in stoneblock while fooling around, and found AvaritiaAddons wasn't installed.  I tried installing the 1.12.2-1.2 version, as well as updating to WanionLib 2.5.  The result is an issue with UniDict
[crash-2022-11-15_18.54.08-client.txt](https://github.com/WanionCane/WanionLib/files/10017757/crash-2022-11-15_18.54.08-client.txt)
I'd love to be able to play with infinity chests (I can't be arsed to learn AE2's nonsense, especially in stoneblock).  Is there any way I can solve this issue or a version I can download that won't cause it?

**Comment by WanionCane** [comment]
Hello, could you try updating UniDict, WanionLib, and Avaritiaddons to their lastest versions?
thank you =D

**Comment by TheDisturbedDragon** [comment]
Will do, thanks.
