### ISSUE TITLE
[1.12.1] Immersive Engineering integration problems

### ISSUE THREAD

**Issue by UnPure** [WanionCane/WanionLib#2]
This is probably related to https://github.com/WanionCane/WanionLib/issues/1
On server start, i get this error
https://pastebin.com/Qy31QVN6

Full log: https://pastebin.com/DvWWF64P

Wanion Lib: 1.12.1-1.0
UniDict: 1.12.1-1.0
Forge: 14.22.0.2475

**Comment by WanionCane** [comment]
this is an UniDict issue, but, for now,  I suggest you to turn off Immersive Engineering Integration.
