### ISSUE TITLE
Mod not marked as supporting 1.12.2

### ISSUE THREAD

**Issue by C0rn3j** [WanionCane/WanionLib#3]
Hi, this mod is not marked as 1.12.2. I assume it works on that version since there's a 1.12.1 marked version.

https://minecraft.curseforge.com/projects/wanionlib/files
please mark the 1.12.1 file as 1.12.2 too.

This "broke" my updater script.

This is also an issue with Unidict, though I'm not sure if .2 actually works in the current mod state?

https://github.com/WanionCane/UniDict/issues/39

**Comment by WanionCane** [comment]
sorry for the late asnwer, the official 1.12.2 version was released in oct 29.
