### ISSUE TITLE
WanionLib : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by unloveddolphin** [WanionCane/WanionLib#5]
so idk what to do i love the stuff it has to it and dont want it removed it but iv tried newer and later vershens

**Comment by WanionCane** [comment]
I have no clue about this error

**Comment by Jueo** [comment]
That's related to Java, in specific about the Java version, here is a list: 

Java SE 10 = 54
Java SE 9 = 53
Java SE 8 = 52
Java SE 7 = 51

I think it's saying that it doesn't support Java 8? I have no clue but this is all I could gather

Here is a link explaining it: https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

**Comment by unloveddolphin** [comment]
hi jorsie I do not under stand what u are having problems with. java 8 does
not support a lot of things.
